class DataInfoCar {
  List<String> make = [
    "ABARTH",
    "AIXAM",
    "AJS",
    "ALEXANDER DENNIS",
    "ALFA ROMEO",
    "ALPINE",
    "APRILIA",
    "ASTON MARTIN",
    "AUDI",
    "BEDFORD",
    "BENELLI",
    "BENTLEY",
    "BMW",
    "CADILLAC",
    "CAETANO",
    "CHAUSSON",
    "CHEVROLET",
    "CHEVROLET GMC",
    "CHRYSLER",
    "CITROEN",
    "COLEMAN MILNE",
    "CUPRA",
    "DACIA",
    "DAEWOO",
    "DAF",
    "DAF TRUCKS",
    "DAIHATSU",
    "DENNIS",
    "DETHLEFFS",
    "DODGE",
    "DODGE (USA)",
    "DS",
    "DUCATI",
    "FERRARI",
    "FIAT",
    "FORD",
    "GENESIS",
    "GOUPIL",
    "HARLEY-DAVIDSON",
    "HONDA",
    "HYUNDAI",
    "INFINITI",
    "IRIS.BUS",
    "ISUZU",
    "ISUZU TRUCKS",
    "IVECO",
    "IVECO-FORD",
    "JAGUAR",
    "JCB",
    "JEEP",
    "KAWASAKI",
    "KIA",
    "KTM",
    "KUBOTA",
    "KYMCO",
    "LAMBORGHINI",
    "LAND ROVER",
    "LDV",
    "LEVC",
    "LEXMOTO",
    "LEXUS",
    "LIEBHERR",
    "LONDON TAXIS INT",
    "LOTUS",
    "MAN",
    "MANITOU",
    "MASERATI",
    "MAXUS",
    "MAZDA",
    "MCC",
    "MCLAREN",
    "MERCEDES",
    "MERCEDES-BENZ",
    "MG",
    "MINI",
    "MITSUBISHI",
    "MITSUBISHI FUSO",
    "MORRIS",
    "NECO",
    "NEOPLAN",
    "NISSAN",
    "OPEL",
    "PERODUA",
    "PEUGEOT",
    "PIAGGIO",
    "POLESTAR",
    "PORSCHE",
    "PROTON",
    "RELIANT",
    "RENAULT",
    "RENAULT TRUCKS",
    "ROLLS ROYCE",
    "ROVER",
    "SAAB",
    "SCANIA",
    "SEAT",
    "SETRA",
    "SKODA",
    "SMART",
    "SSANGYONG",
    "SUBARU",
    "SUZUKI",
    "SYM",
    "TALBOT",
    "TESLA",
    "TOYOTA",
    "TRIGANO",
    "TRIUMPH",
    "TVR",
    "VAUXHALL",
    "VDL",
    "VOLKSWAGEN",
    "VOLVO",
    "WESTFIELD",
    "YAMAHA"
  ];
  List<String> get data {
    return [...make];
  }

  List<String> color = [
    "BEIGE",
    "BLACK",
    "BLUE2",
    "BRONZE",
    "BROWN",
    "CREAM",
    "GOLD",
    "GREEN",
    "GREY",
    "MAROON",
    "MULTI-COLOUR",
    "NOT STATED",
    "ORANGE",
    "PINK",
    "PURPLE",
    "RED",
    "SILVER",
    "TURQUOISE",
    "WHITE",
    "YELLOW",
  ];
}
