class DataInfoCar {
  List<String> make = [
    "Abarth",
    "Bentley",
    "Cadillac",
    "Dacia",
    "Ferrari",
    "Gilbern",
    "Hillman",
    "Infiniti",
    "Jaguar",
    "Kia",
    "Lada",
    "Maserati",
    "Nissan",
    "Opel",
    "Packard",
    "Radical",
    "Saab",
    "Tesla",
    "Ultima",
    "Vauxhall",
    "Westfield",
    "Yamaha",
    "Alfa Romeo",
    "BMW",
    "Caterham",
    "Daewoo",
    "Fiat",
    "GMC",
    "Holden",
    "Isuzu",
    "Jeep",
    "Koenigsegg",
    "Lamborghini",
    "Maxus",
    "Noble",
    "Panther",
    "Reliant",
    "SEAT",
    "Toyota",
    "Volkswagen",
    "Alpine",
    "Bugatti",
    "Chevrolet",
    "Daihatsu",
    "Ford",
    "Great Wall",
    "Honda",
    "Iveco",
    "Jensen",
    "Lancia",
    "Maybach",
    "Nardini",
    "Peugeot",
    "Renault",
    "Shelby",
    "Triumph",
    "Volvo",
    "Ariel",
    "Buick",
    "Chrysler",
    "Daimler",
    "GBS",
    "Hummer",
    "JBA ",
    "Land Rover",
    "Mazda",
    "Perodua",
    "Rover",
    "Skoda",
    "TVR",
    "Aston Martin",
    "Beauford ",
    "Cupra",
    "Datsun",
    "Gardener ",
    "Hyundai",
    "LEVC",
    "McLaren",
    "Polaris",
    "Royale",
    "Smart",
    "Audi",
    "Bramwith",
    "Chesil",
    "De Tomaso",
    "Genesis Motor",
    "Lexus",
    "Mercedes-Benz",
    "Polestar",
    "Rage",
    "Spyker",
    "Austin",
    "Corvette",
    "DFSK",
    "Leyland",
    "Mercury",
    "Pontiac",
    "Reva",
    "SsangYong",
    "AC",
    "Crendon",
    "Dodge",
    "Lincoln",
    "MG",
    "Porsche",
    "Robin Hood ",
    "Subaru",
    "AK",
    "Custom Vehicle",
    "DS Automobiles",
    "Lotus",
    "Microcar",
    "Proton",
    "Rolls-Royce",
    "Sunbeam",
    "Aixam",
    "Dax",
    "London Taxis International",
    "MINI",
    "Suzuki",
    "Mitsubishi",
    "Morgan",
    "Morris",
    "MK",
    "Moke"
  ];
  List<String> get data {
    return [...make];
  }

  List<String> color = [
    "Brown",
    "Blue",
    "Gold",
    "Purple",
    "Silver",
    "Yellow",
    "Green",
    "Navy",
    "Red",
    "White",
    "Orange"
  ];
}
