on:
  push:
    branches:
      - release/*

env:
  MAKE_BUILD_ENV: make build-product
  FLUTTER_APP_SOURCE: "build/app/outputs/apk/release/app-release.apk"
  FLUTTER_VERSION: "3.7.1"
  BLOB_STORAGE_CONTAINER_NAME: "${{ secrets.PROD_BLOB_STORAGE_CONTAINER_NAME }}"
  BLOB_STORAGE_ACCOUNT_NAME: "${{ secrets.PROD_BLOB_STORAGE_ACCOUNT_NAME }}"
  BLOB_STORAGE_ACCOUNT_KEY: "${{ secrets.PROD_BLOB_STORAGE_ACCOUNT_KEY }}"
  AZURE_TENANT_ID: "${{ secrets.PROD_AZURE_TENANT_ID }}"
  AZURE_CLIENT_ID: "${{ secrets.PROD_AZURE_CLIENT_ID }}"
  AZURE_CLIENT_SECRET: "${{ secrets.PROD_AZURE_CLIENT_SECRET }}"

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace build version
        run: |
          export BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/release/})
          sed -i "s/version: .*/version: $BRANCH_NAME+1/" pubspec.yaml

      - name: Use Flutter ${{ env.FLUTTER_VERSION }}
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Build APK
        run: ${{ env.MAKE_BUILD_ENV }}

      - name: Upload APK to Azure Blob Storage
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az login --service-principal -u ${{ env.AZURE_CLIENT_ID }} -p ${{ env.AZURE_CLIENT_SECRET }} --tenant ${{ env.AZURE_TENANT_ID }}
            az storage blob upload -f ${{ env.FLUTTER_APP_SOURCE }} -c ${{ env.BLOB_STORAGE_CONTAINER_NAME }} -n iTicket_latest.apk --account-name ${{ env.BLOB_STORAGE_ACCOUNT_NAME }} --account-key ${{ env.BLOB_STORAGE_ACCOUNT_KEY }}
